language: node_js

node_js:
  - 12

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY 
  bucket: "insa-csb.education"
  region: "us-east-2"

after_success:
  - chmod +x cloudfront-invalidation.sh
  - "./cloudfront-invalidation.sh"

